name: Tag version

on:
  push:
    branches:
      - "ip/release-job"

jobs:
  tag:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Create latest tag
        uses: livepeer/action-gh-release-tags@v0
      - name: Tag
        run: git tag "${{ steps.tags.outputs.tags }}"
      - name: Push
        run: git push --tags"
